# --------------------------------------------------------------------------
# TOML geometry input file
# ========================
# Reference to learn TOML: https://learnxinyminutes.com/docs/toml/
# --------------------------------------------------------------------------

name      = 'Birds' # 'Dummy'

# --------------------------------------------------------------------------
# Swarm initial geometry
# --------------------------------------------------------------------------
[ Geometry ]
r       = 1                 # size of the boids
R       = 1                 # radius of influence of boids
v       = 1                 # speed of the boids
eta     = np.pi/2           # range of random phase change
N       = 1                 # number of boids
seed    = 1                 # random seed

## --------------------------------------------------------------------------
## Applied forces
## --------------------------------------------------------------------------
#[[ Forces ]]
#point     = 1                # [-]
#axis      = 1                # 0 for force along x axis, 1 for force along y
#magnitude = -1000          # [N]


## --------------------------------------------------------------------------
## Boundary conditions
## --------------------------------------------------------------------------
[[ BoundaryConditions]]
#for box
L           = 10            # size of box
periodic_bc = True      # Are the boundaries periodic? Otherwise, hard

## --------------------------------------------------------------------------
## Simulation conditions
## --------------------------------------------------------------------------
[[ SimulationConditions]]
T           = 10            # time of simulation
dt          = 1             # simulation step

## --------------------------------------------------------------------------
## Output settings
## --------------------------------------------------------------------------
#[ Output ]
#nFreq      = 5               # [-] number of eigenfrequencies displayed
#plot_scale = 1              # [-] displacement plot scale
#
